#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ComeTogether.Droid.Resource", IsApplication=true)]

namespace ComeTogether.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_right = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_up = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int context_menu = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int icon_search = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090015
			public const int AddButton = 2131296277;
			
			// aapt resource value: 0x7f090003
			public const int AddCategoryButton = 2131296259;
			
			// aapt resource value: 0x7f090011
			public const int CancelDeleteButton = 2131296273;
			
			// aapt resource value: 0x7f090002
			public const int CategoryList = 2131296258;
			
			// aapt resource value: 0x7f090000
			public const int CategoryName = 2131296256;
			
			// aapt resource value: 0x7f09000e
			public const int ChangeDateFinishButton = 2131296270;
			
			// aapt resource value: 0x7f09000a
			public const int DateAddedLabel = 2131296266;
			
			// aapt resource value: 0x7f09000b
			public const int DateAddedText = 2131296267;
			
			// aapt resource value: 0x7f09000c
			public const int DateFinishLabel = 2131296268;
			
			// aapt resource value: 0x7f09000d
			public const int DateFinishText = 2131296269;
			
			// aapt resource value: 0x7f090007
			public const int LabelTaskText = 2131296263;
			
			// aapt resource value: 0x7f090013
			public const int NameText = 2131296275;
			
			// aapt resource value: 0x7f090014
			public const int NotesText = 2131296276;
			
			// aapt resource value: 0x7f090010
			public const int SaveButton = 2131296272;
			
			// aapt resource value: 0x7f090017
			public const int StatusHeader = 2131296279;
			
			// aapt resource value: 0x7f090008
			public const int TaskDetailsHeader = 2131296264;
			
			// aapt resource value: 0x7f090018
			public const int TaskList = 2131296280;
			
			// aapt resource value: 0x7f090016
			public const int TaskNameHeader = 2131296278;
			
			// aapt resource value: 0x7f090009
			public const int TaskText = 2131296265;
			
			// aapt resource value: 0x7f09000f
			public const int chkDone = 2131296271;
			
			// aapt resource value: 0x7f090006
			public const int dlgBtnAddNewCategory = 2131296262;
			
			// aapt resource value: 0x7f090005
			public const int dlgCategoryName = 2131296261;
			
			// aapt resource value: 0x7f090012
			public const int lstItemTask = 2131296274;
			
			// aapt resource value: 0x7f090001
			public const int lvContainer = 2131296257;
			
			// aapt resource value: 0x7f090019
			public const int search = 2131296281;
			
			// aapt resource value: 0x7f090004
			public const int searchCategoryET = 2131296260;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CategoryListItem = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CategoryScreen = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int dialog_AddNewCategory = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int TaskDetails = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int TaskListItem = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int TasksScreen = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int menu = 2131230720;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050004
			public const int add_category = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int btn_date_to_done = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int date_added = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int date_to_done = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int tasks_text = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070002
			public const int GreenActionBar = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int Theme_Tasky = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int WhiteTitleText = 2131165187;
			
			// aapt resource value: 0x7f070000
			public const int dialog_add_category_animation = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
